# Generated by Django 5.1 on 2024-08-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='created_at',
        ),
    ]
